services:
  db:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [appnet]

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [appnet]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    depends_on:
      keycloak-db:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks: [appnet]

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring-api
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: apppass
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/app
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started
    ports:
      - "8080:8080"
    networks: [appnet]

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next-front
    environment:
      # URL que le navigateur utilise (donc localhost)
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080
      NEXT_PUBLIC_KEYCLOAK_ISSUER: http://localhost:8081/realms/app
      NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: nextjs
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks: [appnet]

volumes:
  db_data:
  keycloak_db_data:

networks:
  appnet:
